version: 2
jobs:
  server:
    working_directory: ~/url-shortener/server
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%
          - MYSQL_ROOT_PASSWORD=
          - MYSQL_DATABASE=url-shortener
    steps:
      - checkout:
          path: ~/url-shortener
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: "Generate Coverage"
          command: |
            go test -tags sql -coverpkg=./... -coverprofile=coverage.txt ./...
      - run:
          name: "Publish Coverage to Coveralls.io"
          command: |
            go get github.com/mattn/goveralls
            goveralls -coverprofile=coverage.txt -service semaphore -repotoken $COVERALLS_REPO_TOKEN
  client:
    working_directory: ~/url-shortener/client
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout:
          path: ~/url-shortener
      - restore_cache:
          key: url-shortener-client-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: url-shortener-client-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Lint
          command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run test:ci
      - run:
          name: Coveralls
          command: cat ./coverage/url-shortener/lcov.info  | ./node_modules/coveralls/bin/coveralls.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - client
