version: 2
jobs:
  server:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: "Generate Coverage"
          command: |
            cd server && go test -tags sql -coverpkg=./... -coverprofile=coverage.txt ./...
      - run:
          name: "Publish Coverage to Coveralls.io"
          command: |
            go get github.com/mattn/goveralls
            cd server && goveralls -coverprofile=coverage.txt -service semaphore -repotoken $COVERALLS_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
