version: 2
jobs:
  server:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: "Generate Coverage"
          command: |
            cd /server && go test -coverpkg=./... -coverprofile=coverage.txt ./...
      - run:
          name: "Publish Coverage to Coveralls.io"
          command: |
            go get github.com/mattn/goveralls
            cd /server && goveralls -coverprofile=coverage.txt -service semaphore -repotoken $COVERALLS_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
